package com.InsuranceManagementSystem.AdminService.enums;

public enum AuditAction {

    APPROVE_CLAIM,
    REJECT_CLAIM,
    SETTLE_CLAIM,
    START_CLAIM_REVIEW,
    VIEW_CLAIM,
    VIEW_ALL_CLAIMS,
    VIEW_PENDING_CLAIMS,

    CREATE_POLICY_PRODUCT,
    UPDATE_POLICY_PRODUCT,
    DEACTIVATE_POLICY_PRODUCT,
    REACTIVATE_POLICY_PRODUCT,
    VIEW_POLICY_PRODUCT,
    VIEW_ALL_POLICY_PRODUCTS,

    CREATE_ADMIN,
    VIEW_ALL_USERS,
    VIEW_USER,
    VIEW_USERS_BY_ROLE,

    VIEW_DASHBOARD,
    VIEW_POLICY_REPORT,
    VIEW_CLAIMS_REPORT,
    VIEW_REVENUE_REPORT,
    VIEW_AUDIT_LOGS
}