server.port=8888

spring.application.name=ConfigServer

spring.cloud.config.server.git.uri=https://github.com/yasaswini18/insurance_config_repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.username=${GITHUB_USERNAME}
spring.cloud.config.server.git.password=${GITHUB_TOKEN}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost